name       : obmenu
version    : 1.0
release    : 1
source     :
    - http://downloads.sourceforge.net/obmenu/obmenu-1.0.tar.gz : c9cea64d40d461a34ea3bdaec9867487c819d5f9814e1cc54db607d4d3c20e27
license    : GPL-2.0 
component  : desktop
summary    : Openbox menu editing made easy
description: |
    Obmenu is a menu editor designed for openbox. It's easy to use, allowing to get the most out of the powerful Openbox menu system, while hiding the xml layout from the user.
setup      : |
    %python_setup
install    : |
    %python_install
